### ISSUE TITLE
errors due to versions differences

### ISSUE THREAD

**Issue by amrhamedp** [salilab/cryptosite#1]
Hello,
I am trying to get cryptosite working however it seems that new versions of the dependencies are not compatible. For example ,usearch no longer has --cluster option and doesn't have --usersort option.
Another example the blast parsing:
   mod.main()
  File "/home/cresset/anaconda2/envs/cryptosite/lib/python2.7/cryptosite/setup.py", line 210, in main
    setup(pdb, chains, short)
  File "/home/cresset/anaconda2/envs/cryptosite/lib/python2.7/cryptosite/setup.py", line 98, in setup
    sbjctSeq)
  File "/home/cresset/anaconda2/envs/cryptosite/lib/python2.7/cryptosite/seq_conservation.py", line 77, in parse_blast
    ma = 1./Clusters[sseq]
KeyError: u'H8YG881'
[1]+  Done                    gedit /home/cresset/anaconda2/envs/cryptosite/lib/python2.7/cryptosite/seq_conservation.py

Can you please specify the versions of the dependencies that work on the server......blast,usearch and all other dependencies

**Comment by benmwebb** [comment]
Hmm, I'll look into this and see if I can see what's going on with the newer versions of the dependencies. For reference these are the actual versions of each that we use here:

    1) modeller/9.19         6) patch_dock/1.3       11) python/scipy/0.12.1
    2) muscle/3.8.31         7) imp/2.7.0            12) python/scikit/0.12
    3) dssp/2.2.1            8) blast+/2.2.28  
    4) fpocket/2.0           9) usearch/4.0.43
    5) concavity/0.1        10) python/numpy/1.10.2

**Comment by benmwebb** [comment]
OK, it should work with more recent versions of USEARCH now. Give it a go and see if it fixes the problems you're seeing.

As for the BLAST parsing error you reported, that's using the results from USEARCH, so you must have modified the code to get past USEARCH failing? Hopefully with the fix above this problem should be resolved too.

**Comment by georopon** [comment]
Hi, How I can install cryptosite on mac or linux, and run it? , There is some guidelines?

**Comment by benmwebb** [comment]
> Hi, How I can install cryptosite on mac or linux, and run it? , There is some guidelines?

Please don't reopen an entirely unrelated issue to ask questions. That being said, installation instructions [are in the manual](https://cryptosite.readthedocs.io/en/latest/installation.html).
